CREATE SEQUENCE SEQ_SENSOR
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE SEQ_LEITURA
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE SEQ_ALERTA
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE SEQ_PRECISAO_CHUVA
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE SEQ_CONTROLE_IRRIGACAO
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE SEQUENCE SEQ_USUARIOS
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE TBL_SENSOR (
   ID_SENSOR INTEGER DEFAULT SEQ_SENSOR.NEXTVAL NOT NULL,
   TIPO_SENSOR VARCHAR2(50) NOT NULL,
   LOCALIZACAO VARCHAR2(100) NOT NULL,
);

CREATE TABLE TBL_LEITURA (
   ID_LEITURA INTEGER DEFAULT SEQ_LEITURA.NEXTVAL NOT NULL,
   VALOR FLOAT NOT NULL,
   DATA_HORA TIMESTAMP NOT NULL,
   ID_SENSOR INTEGER NOT NULL,
);

CREATE TABLE TBL_ALERTA (
   ID_ALERTA INTEGER DEFAULT SEQ_ALERTA.NEXTVAL NOT NULL,
   TIPO_ALERTA VARCHAR2(50) NOT NULL,
   DESCRICAO VARCHAR2(255) NOT NULL,
   DATA_HORA TIMESTAMP NOT NULL,
);

CREATE TABLE TBL_PREVISAO_CHUVA (
   ID_PREVISAO INTEGER DEFAULT SEQ_PRECISAO_CHUVA.NEXTVAL NOT NULL,
   DATA_PREVISAO DATE NOT NULL,
   PREVISAO VARCHAR2(255) NOT NULL,
);

CREATE TABLE TBL_CONTROLE_IRRIGACAO (
   ID_CONTROLE INTEGER DEFAULT SEQ_CONTROLE_IRRIGACAO.NEXTVAL NOT NULL,
   LOCALIZACAO VARCHAR2(100) NOT NULL,
   ESTADO VARCHAR2(20) NOT NULL,
   DATA_HORA TIMESTAMP NOT NULL,
   ID_PREVISAO INTEGER NOT NULL,
);

CREATE TABLE TBL_USUARIOS(
   ID_USUARIO INTEGER DEFAULT SEQ_USUARIOS.NEXTVAL NOT NULL,
   NOME VARCHAR2(100) NOT NULL,
   EMAIL VARCHAR2(100) UNIQUE NOT NULL,
   SENHA VARCHAR2(100) NOT NULL
   ROLE VARCHAR2(50) DEFAULT 'USER'
);

--INSERT INTO TBL_SENSOR (ID_SENSOR, TIPO_SENSOR, LOCALIZACAO) VALUES (SEQ_SENSOR.NEXTVAL, 'Sensor de Qualidade do Ar', 'Parque Ibirapuera');
--INSERT INTO TBL_SENSOR (ID_SENSOR, TIPO_SENSOR, LOCALIZACAO) VALUES (SEQ_SENSOR.NEXTVAL, 'Sensor de Umidade do Solo', 'Parque Ibirapuera');
--INSERT INTO TBL_SENSOR (ID_SENSOR, TIPO_SENSOR, LOCALIZACAO) VALUES (SEQ_SENSOR.NEXTVAL, 'Sensor de Temperatura', 'Parque Ibirapuera');
--INSERT INTO TBL_SENSOR (ID_SENSOR, TIPO_SENSOR, LOCALIZACAO) VALUES (SEQ_SENSOR.NEXTVAL, 'Sensor de Qualidade do Ar', 'Parque Villa-Lobos');
--INSERT INTO TBL_SENSOR (ID_SENSOR, TIPO_SENSOR, LOCALIZACAO) VALUES (SEQ_SENSOR.NEXTVAL, 'Sensor de Umidade do Solo', 'Parque Villa-Lobos');
--INSERT INTO TBL_SENSOR (ID_SENSOR, TIPO_SENSOR, LOCALIZACAO) VALUES (SEQ_SENSOR.NEXTVAL, 'Sensor de Temperatura', 'Parque Villa-Lobos');